# Use the official Django image as the base image
FROM python:3.11-slim-buster

# Set the working directory
WORKDIR /backend

COPY backend/ .
RUN ls -la
# Install the Django application dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Django application into the container


# Expose the port the app runs on
EXPOSE 8000

# Command to run the application
CMD ["gunicorn", "core.wsgi:application", "--bind", "0.0.0.0:8000"]
