version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-Backend
    ports:
      - "8000:8000"
      - "5678:5678"
    environment:
      - DJANGO_DEBUG=true

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-Frontend
    ports:
      - "3000:3000"
