version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-Backend
    ports:
      - "${BACKEND_PORT:-8000}:8000"
      - "${BACKEND_DEBUG_PORT:-5678}:5678"
    environment:
      - DJANGO_DEBUG=true

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-Frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"